/**
 * Seed do registry municipal: as 55 Câmaras do PR com mandato de vereador
 * comprovado no histórico dos 428 candidatos.
 *
 * Este arquivo é dado verificado à mão, não resultado de sondagem automática.
 * Cada `apiBaseUrl` aqui foi acessado e devolveu JSON; cada `access` reflete o
 * que a verificação encontrou. As câmaras sem `apiBaseUrl` ficam com
 * `capabilities` toda falsa — a regra é não afirmar o que não se viu.
 *
 * Verificação de: 2026-09-30
 *
 * Contagem: 26 com SAPL acessível, 1 atrás de WAF (Curitiba), 1 com API que
 * exige token (Londrina), 1 só em HTML (Ponta Grossa), 26 sem fonte localizada.
 *
 * Para incluir outra Câmara: acrescentar o município em `municipalities-pr.ts`
 * (com o código do IBGE) e o registro aqui.
 */

import { NO_CAPABILITIES } from './types.ts'
import type { MunicipalChamberSource } from './types.ts'

export interface SeedChamber {
  ibgeCode: string
  municipalityName: string
  state: string
  chamberName: string
  chamberUrl: string | null
  sourceType: MunicipalChamberSource['sourceType']
  apiBaseUrl: string | null
  access: MunicipalChamberSource['access']
  note?: string
  /** Candidatos-vereador do histórico do TSE neste município. */
  candidates: number
}

const SEEDS: readonly SeedChamber[] = [
  {
    ibgeCode: '4100301',
    municipalityName: 'Agudos do Sul',
    state: 'PR',
    chamberName: 'Câmara Municipal de Agudos do Sul',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4100400',
    municipalityName: 'Almirante Tamandaré',
    state: 'PR',
    chamberName: 'Câmara Municipal de Almirante Tamandaré',
    chamberUrl: 'https://sapl.almirantetamandare.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.almirantetamandare.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4100608',
    municipalityName: 'Alto Paraná',
    state: 'PR',
    chamberName: 'Câmara Municipal de Alto Paraná',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4101101',
    municipalityName: 'Andirá',
    state: 'PR',
    chamberName: 'Câmara Municipal de Andirá',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4101408',
    municipalityName: 'Apucarana',
    state: 'PR',
    chamberName: 'Câmara Municipal de Apucarana',
    chamberUrl: 'https://sapl.apucarana.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.apucarana.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4101804',
    municipalityName: 'Araucária',
    state: 'PR',
    chamberName: 'Câmara Municipal de Araucária',
    chamberUrl: 'https://sapl.araucaria.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.araucaria.pr.leg.br/',
    access: 'verified',
    candidates: 3,
  },
  {
    ibgeCode: '4102307',
    municipalityName: 'Balsa Nova',
    state: 'PR',
    chamberName: 'Câmara Municipal de Balsa Nova',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4102406',
    municipalityName: 'Bandeirantes',
    state: 'PR',
    chamberName: 'Câmara Municipal de Bandeirantes',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4103602',
    municipalityName: 'Cambará',
    state: 'PR',
    chamberName: 'Câmara Municipal de Cambará',
    chamberUrl: 'https://sapl.cambara.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.cambara.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4103701',
    municipalityName: 'Cambé',
    state: 'PR',
    chamberName: 'Câmara Municipal de Cambé',
    chamberUrl: 'https://sapl.cambe.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.cambe.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4104204',
    municipalityName: 'Campo Largo',
    state: 'PR',
    chamberName: 'Câmara Municipal de Campo Largo',
    chamberUrl: 'https://sapl.campolargo.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.campolargo.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4104253',
    municipalityName: 'Campo Magro',
    state: 'PR',
    chamberName: 'Câmara Municipal de Campo Magro',
    chamberUrl: 'https://sapl.campomagro.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.campomagro.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4104303',
    municipalityName: 'Campo Mourão',
    state: 'PR',
    chamberName: 'Câmara Municipal de Campo Mourão',
    chamberUrl: 'https://sapl.campomourao.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.campomourao.pr.leg.br/',
    access: 'verified',
    candidates: 3,
  },
  {
    ibgeCode: '4104808',
    municipalityName: 'Cascavel',
    state: 'PR',
    chamberName: 'Câmara Municipal de Cascavel',
    chamberUrl: 'https://sapl.cascavel.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.cascavel.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4104907',
    municipalityName: 'Castro',
    state: 'PR',
    chamberName: 'Câmara Municipal de Castro',
    chamberUrl: 'https://sapl.castro.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.castro.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4105508',
    municipalityName: 'Cianorte',
    state: 'PR',
    chamberName: 'Câmara Municipal de Cianorte',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'blocked',
    note: 'O SAPL no domínio oficial respondeu HTML em 2026-09-30 (a URL /api/ devolve a página do portal, não JSON), então não há leitura programática. Fora da Fase 1: só com confirmação do órgão sobre um endpoint oficial.',
    candidates: 1,
  },
  {
    ibgeCode: '4105706',
    municipalityName: 'Clevelândia',
    state: 'PR',
    chamberName: 'Câmara Municipal de Clevelândia',
    chamberUrl: 'https://sapl.clevelandia.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.clevelandia.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4105805',
    municipalityName: 'Colombo',
    state: 'PR',
    chamberName: 'Câmara Municipal de Colombo',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 3,
  },
  {
    ibgeCode: '4105904',
    municipalityName: 'Colorado',
    state: 'PR',
    chamberName: 'Câmara Municipal de Colorado',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4106407',
    municipalityName: 'Cornélio Procópio',
    state: 'PR',
    chamberName: 'Câmara Municipal de Cornélio Procópio',
    chamberUrl: 'https://sapl.cornelioprocopio.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.cornelioprocopio.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4106506',
    municipalityName: 'Coronel Vivida',
    state: 'PR',
    chamberName: 'Câmara Municipal de Coronel Vivida',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4106902',
    municipalityName: 'Curitiba',
    state: 'PR',
    chamberName: 'Câmara Municipal de Curitiba',
    chamberUrl: 'https://www.cmc.pr.gov.br/',
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'blocked',
    note: 'SAPL sob WAF: 403 em qualquer cliente não-browser, inclusive na raiz. Não contornar — pedir acesso à CMC ou esperar abertura no portal de dados abertos.',
    candidates: 61,
  },
  {
    ibgeCode: '4107652',
    municipalityName: 'Fazenda Rio Grande',
    state: 'PR',
    chamberName: 'Câmara Municipal de Fazenda Rio Grande',
    chamberUrl: 'https://sapl.fazendariogrande.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.fazendariogrande.pr.leg.br/',
    access: 'verified',
    candidates: 3,
  },
  {
    ibgeCode: '4108304',
    municipalityName: 'Foz do Iguaçu',
    state: 'PR',
    chamberName: 'Câmara Municipal de Foz do Iguaçu',
    chamberUrl: 'https://sapl.fozdoiguacu.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.fozdoiguacu.pr.leg.br/',
    access: 'verified',
    candidates: 5,
  },
  {
    ibgeCode: '4108320',
    municipalityName: 'Francisco Alves',
    state: 'PR',
    chamberName: 'Câmara Municipal de Francisco Alves',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4109302',
    municipalityName: 'Guaraniaçu',
    state: 'PR',
    chamberName: 'Câmara Municipal de Guaraniaçu',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4109401',
    municipalityName: 'Guarapuava',
    state: 'PR',
    chamberName: 'Câmara Municipal de Guarapuava',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 5,
  },
  {
    ibgeCode: '4109807',
    municipalityName: 'Ibiporã',
    state: 'PR',
    chamberName: 'Câmara Municipal de Ibiporã',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 3,
  },
  {
    ibgeCode: '4113007',
    municipalityName: 'Jussara',
    state: 'PR',
    chamberName: 'Câmara Municipal de Jussara',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4113700',
    municipalityName: 'Londrina',
    state: 'PR',
    chamberName: 'Câmara Municipal de Londrina',
    chamberUrl: 'https://www.cml.pr.gov.br/dadosabertos',
    sourceType: 'official-api',
    apiBaseUrl: null,
    access: 'requires-auth',
    note: 'API real (vereadores, proposicoes, pautas), mas exige token de acesso obtido por cadastro. Fora da Fase 1: adapter próprio depois que houver token.',
    candidates: 10,
  },
  {
    ibgeCode: '4114708',
    municipalityName: 'Maria Helena',
    state: 'PR',
    chamberName: 'Câmara Municipal de Maria Helena',
    chamberUrl: 'https://sapl.mariahelena.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.mariahelena.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4115200',
    municipalityName: 'Maringá',
    state: 'PR',
    chamberName: 'Câmara Municipal de Maringá',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'blocked',
    note: 'O SAPL no domínio oficial respondeu HTML em 2026-09-30 (a URL /api/ devolve a página do portal, não JSON), então não há leitura programática. Fora da Fase 1: só com confirmação do órgão sobre um endpoint oficial.',
    candidates: 8,
  },
  {
    ibgeCode: '4115705',
    municipalityName: 'Matinhos',
    state: 'PR',
    chamberName: 'Câmara Municipal de Matinhos',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4117305',
    municipalityName: 'Ortigueira',
    state: 'PR',
    chamberName: 'Câmara Municipal de Ortigueira',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4118204',
    municipalityName: 'Paranaguá',
    state: 'PR',
    chamberName: 'Câmara Municipal de Paranaguá',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'blocked',
    note: 'O SAPL no domínio oficial respondeu HTML em 2026-09-30 (a URL /api/ devolve a página do portal, não JSON), então não há leitura programática. Fora da Fase 1: só com confirmação do órgão sobre um endpoint oficial.',
    candidates: 1,
  },
  {
    ibgeCode: '4118402',
    municipalityName: 'Paranavaí',
    state: 'PR',
    chamberName: 'Câmara Municipal de Paranavaí',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4118501',
    municipalityName: 'Pato Branco',
    state: 'PR',
    chamberName: 'Câmara Municipal de Pato Branco',
    chamberUrl: 'https://sapl.patobranco.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.patobranco.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4119152',
    municipalityName: 'Pinhais',
    state: 'PR',
    chamberName: 'Câmara Municipal de Pinhais',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4119509',
    municipalityName: 'Piraquara',
    state: 'PR',
    chamberName: 'Câmara Municipal de Piraquara',
    chamberUrl: 'https://sapl.piraquara.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.piraquara.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4119608',
    municipalityName: 'Pitanga',
    state: 'PR',
    chamberName: 'Câmara Municipal de Pitanga',
    chamberUrl: 'https://sapl.pitanga.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.pitanga.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4119905',
    municipalityName: 'Ponta Grossa',
    state: 'PR',
    chamberName: 'Câmara Municipal de Ponta Grossa',
    chamberUrl: 'https://www.pontagrossa.pr.leg.br/',
    sourceType: 'official-web',
    apiBaseUrl: null,
    access: 'html-only',
    note: 'Não usa SAPL: é Plone, só HTML (/processo-legislativo/proposicao, /projeto). Sem JSON. Fora da Fase 1: scraping seria frágil.',
    candidates: 9,
  },
  {
    ibgeCode: '4119954',
    municipalityName: 'Pontal do Paraná',
    state: 'PR',
    chamberName: 'Câmara Municipal de Pontal do Paraná',
    chamberUrl: 'https://sapl.pontaldoparana.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.pontaldoparana.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4120903',
    municipalityName: 'Quedas do Iguaçu',
    state: 'PR',
    chamberName: 'Câmara Municipal de Quedas do Iguaçu',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4121257',
    municipalityName: 'Ramilândia',
    state: 'PR',
    chamberName: 'Câmara Municipal de Ramilândia',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4122404',
    municipalityName: 'Rolândia',
    state: 'PR',
    chamberName: 'Câmara Municipal de Rolândia',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4125506',
    municipalityName: 'São José dos Pinhais',
    state: 'PR',
    chamberName: 'Câmara Municipal de São José dos Pinhais',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 2,
  },
  {
    ibgeCode: '4125605',
    municipalityName: 'São Mateus do Sul',
    state: 'PR',
    chamberName: 'Câmara Municipal de São Mateus do Sul',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 4,
  },
  {
    ibgeCode: '4126207',
    municipalityName: 'Sapopema',
    state: 'PR',
    chamberName: 'Câmara Municipal de Sapopema',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4126306',
    municipalityName: 'Sengés',
    state: 'PR',
    chamberName: 'Câmara Municipal de Sengés',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4127106',
    municipalityName: 'Telêmaco Borba',
    state: 'PR',
    chamberName: 'Câmara Municipal de Telêmaco Borba',
    chamberUrl: 'https://sapl.telemacoborba.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.telemacoborba.pr.leg.br/',
    access: 'verified',
    candidates: 2,
  },
  {
    ibgeCode: '4127304',
    municipalityName: 'Terra Rica',
    state: 'PR',
    chamberName: 'Câmara Municipal de Terra Rica',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4127403',
    municipalityName: 'Terra Roxa',
    state: 'PR',
    chamberName: 'Câmara Municipal de Terra Roxa',
    chamberUrl: 'https://sapl.terraroxa.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.terraroxa.pr.leg.br/',
    access: 'verified',
    candidates: 1,
  },
  {
    ibgeCode: '4127700',
    municipalityName: 'Toledo',
    state: 'PR',
    chamberName: 'Câmara Municipal de Toledo',
    chamberUrl: 'https://sapl.toledo.pr.leg.br',
    sourceType: 'sapl',
    apiBaseUrl: 'https://sapl.toledo.pr.leg.br/',
    access: 'verified',
    candidates: 4,
  },
  {
    ibgeCode: '4127965',
    municipalityName: 'Turvo',
    state: 'PR',
    chamberName: 'Câmara Municipal de Turvo',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'not-found',
    note: 'Nenhuma fonte localizada em 2026-09-30 (host sapl.<município>.pr.leg.br e variações testadas).',
    candidates: 1,
  },
  {
    ibgeCode: '4128104',
    municipalityName: 'Umuarama',
    state: 'PR',
    chamberName: 'Câmara Municipal de Umuarama',
    chamberUrl: null,
    sourceType: 'unknown',
    apiBaseUrl: null,
    access: 'blocked',
    note: 'O SAPL no domínio oficial respondeu HTML em 2026-09-30 (a URL /api/ devolve a página do portal, não JSON), então não há leitura programática. Fora da Fase 1: só com confirmação do órgão sobre um endpoint oficial.',
    candidates: 1,
  },
]

/** Registry municipal como fontes completas, com capacidades zeradas. */
export function buildSeedSources(): MunicipalChamberSource[] {
  return SEEDS.map((seed) => ({
    municipalityIbgeCode: seed.ibgeCode,
    municipalityName: seed.municipalityName,
    state: seed.state,
    chamberName: seed.chamberName,
    chamberUrl: seed.chamberUrl,
    sourceType: seed.sourceType,
    apiBaseUrl: seed.apiBaseUrl,
    access: seed.access,
    capabilities: { ...NO_CAPABILITIES },
    lastVerifiedAt: '2026-09-30',
    ...(seed.note === undefined ? {} : { note: seed.note }),
  }))
}

/**
 * Pares candidato-município cobertos pelo seed: 177.
 *
 * Não é o número de pessoas. São 169 candidatos-vereador distintos no
 * histórico, e a diferença (8) são candidatos que atuaram em dois municípios
 * — por isso somar por município passa de 169. A ficha nunca soma isto para
 * contar pessoas.
 */
export const SEED_CANDIDATE_MANDATE_COUNT = SEEDS.reduce(
  (sum, chamber) => sum + chamber.candidates,
  0,
)
